[tox]
skip_missing_interpreters=True

[testenv]
commands=
    pip install -e .
    pytest -p no:logging --cov=engineio --cov-branch --cov-report=term-missing --cov-report=xml
deps=
    pytest
    pytest-cov
    pytest-asyncio
    aiohttp
    tornado
    requests
    websocket-client

[testenv:pypy3]

[testenv:flake8]
deps=
    flake8
commands=
    flake8 --exclude=".*" --ignore=W503,E402,E722 src/engineio tests examples

[testenv:docs]
changedir=docs
deps=
    sphinx
    furo
allowlist_externals=
    make
commands=
    make html
